# MD resources (rescomp). tile_pixels.bin is generated by tools/png2md.py.
BIN tile_pixels "tile_pixels.bin" 2
BIN tile_blocks "tile_blocks.bin" 2
BIN tile_op "tile_op.bin" 2
BIN tile_cm "tile_cm.bin" 2
BIN title_tiles "title_tiles.bin" 2
BIN title_map "title_map.bin" 2
BIN title_pal "title_pal.bin" 2
BIN mcl_v00 "mcl_v00.bin" 2
BIN mcl_v01 "mcl_v01.bin" 2
BIN mcl_v02 "mcl_v02.bin" 2
BIN mcl_v03 "mcl_v03.bin" 2
BIN mcl_v04 "mcl_v04.bin" 2
BIN mcl_v05 "mcl_v05.bin" 2
BIN mcl_v06 "mcl_v06.bin" 2
BIN mcl_v07 "mcl_v07.bin" 2
BIN mcl_v08 "mcl_v08.bin" 2
BIN mcl_v09 "mcl_v09.bin" 2
BIN mcl_v10 "mcl_v10.bin" 2
BIN mcl_v11 "mcl_v11.bin" 2
BIN mcl_v12 "mcl_v12.bin" 2
BIN mcl_v13 "mcl_v13.bin" 2
BIN mcl_v14 "mcl_v14.bin" 2
BIN mcl_v15 "mcl_v15.bin" 2
WAV sfx_00 "sfx/sfx_00.wav" XGM2 13300
WAV sfx_01 "sfx/sfx_01.wav" XGM2 13300
WAV sfx_02 "sfx/sfx_02.wav" XGM2 13300
WAV sfx_03 "sfx/sfx_03.wav" XGM2 13300
WAV sfx_04 "sfx/sfx_04.wav" XGM2 13300
WAV sfx_05 "sfx/sfx_05.wav" XGM2 13300
WAV sfx_06 "sfx/sfx_06.wav" XGM2 13300
WAV sfx_07 "sfx/sfx_07.wav" XGM2 13300
WAV sfx_08 "sfx/sfx_08.wav" XGM2 13300
WAV sfx_09 "sfx/sfx_09.wav" XGM2 13300
WAV sfx_10 "sfx/sfx_10.wav" XGM2 13300
WAV sfx_11 "sfx/sfx_11.wav" XGM2 13300
WAV sfx_12 "sfx/sfx_12.wav" XGM2 13300
WAV sfx_13 "sfx/sfx_13.wav" XGM2 13300
WAV sfx_14 "sfx/sfx_14.wav" XGM2 13300
WAV sfx_15 "sfx/sfx_15.wav" XGM2 13300
BIN music_title "music_title.bin" 2
BIN music_win "music_win.bin" 2
BIN music_lose "music_lose.bin" 2
BIN help_md "help_md.bin" 2
BIN tutorial_md "tutorial_md.bin" 2
BIN lexicon_md "lexicon_md.bin" 2
BIN spells_md "spells_md.bin" 2
BIN pic_win_tiles "pic_win_tiles.bin" 2
BIN pic_win_map "pic_win_map.bin" 2
BIN pic_win_pal "pic_win_pal.bin" 2
BIN pic_lose_tiles "pic_lose_tiles.bin" 2
BIN pic_lose_map "pic_lose_map.bin" 2
BIN pic_lose_pal "pic_lose_pal.bin" 2
