#!/bin/bash
# Host tests of the Mega Drive frontend: md/test/run.sh [game|units] [name-filter[,filter]]
#   game   the game logic (game_md.c) against the real core, SGDK replaced by stubs
#   units  libc subset, scroll bookkeeping, text/bar UI
# Without arguments both run. SANITIZE=1 builds with AddressSanitizer and UBSan.
set -euo pipefail
cd "$(dirname "$0")/../.."
for g in tiles data maps scenarios; do
    [ -f src/core/gen/$g.h ] || { echo "src/core/gen missing - run the generators (uv run tools/build.py --all)" >&2; exit 1; }
done
[ -f md/src/gen/maps_md.h ] || uv run --quiet tools/md_assets.py
[ -f md/src/gen/tiles_md.h ] || uv run --quiet tools/png2md.py
OUT=out/mdtest
mkdir -p "$OUT"
[ -f md/res/help_md.bin ] || uv run --quiet tools/md_help.py
python3 - <<'PY'
from pathlib import Path
out = ["/* generated by md/test/run.sh */"]
for n in ("help_md", "tutorial_md", "lexicon_md", "spells_md", "music_title", "music_win", "music_lose"):
    d = Path("md/res/%s.bin" % n).read_bytes()
    out.append("const unsigned char %s[%d] = {%s};" % (n, len(d), ",".join(str(b) for b in d)))
Path("out/mdtest/res_data.c").write_text("\n".join(out) + "\n")
PY
WHICH="${1:-all}"
FILTER="${2:-}"
SAN=""
if [ "${SANITIZE:-}" = 1 ]; then SAN="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=undefined"; fi   # SANITIZE=1 md/test/run.sh
CFLAGS="$SAN -std=gnu99 -g -O1 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-deprecated-declarations -DVIEW_STATIC_CACHE=2 -Imd/test/stubs -Imd/test -Imd/src -Isrc/core -Isrc/core/gen"
rc=0
if [ "$WHICH" = all ] || [ "$WHICH" = units ]; then
    echo "== units"
    cc $CFLAGS -o "$OUT/test_units" md/test/test_units.c md/test/stubs_hw.c md/src/libc_md.c
    "$OUT/test_units" $FILTER || rc=1
    echo "== sound"
    cc $CFLAGS -o "$OUT/test_sound" md/test/test_sound.c md/test/stubs_hw.c "$OUT/res_data.c"
    "$OUT/test_sound" $FILTER || rc=1
fi
if [ "$WHICH" = all ] || [ "$WHICH" = game ]; then
    echo "== game"
    # snprintf is the console's own (libc_md.c) here as well: the core and the frontend format with it there
    cc $CFLAGS -Dsnprintf=loc_snprintf -o "$OUT/test_game" md/test/test_game.c md/test/stubs_hw.c md/test/stubs_mod.c "$OUT/res_data.c" \
        md/src/libc_md.c $(ls src/core/*.c) src/core/gen/*.c
    "$OUT/test_game" $FILTER || rc=1
fi
exit $rc
